/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Blockbuster;

import javax.swing.JOptionPane;

/**
 *
 * @author victoriaacuna
 */
public class CreateMovie extends javax.swing.JFrame {

    Pelicula movies[], newMovies[];
    Cartelera c;
    
    public CreateMovie(Pelicula movies[]) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.movies = movies;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        movieID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CreateMovie = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        movieGenre = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 237, 37));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 37));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GÉNERO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 37));
        getContentPane().add(movieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 237, 37));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 22, 37));

        CreateMovie.setText("CREAR");
        CreateMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMovieActionPerformed(evt);
            }
        });
        getContentPane().add(CreateMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 97, 39));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AGREGAR PELÍCULA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 62, -1, 67));

        btnGoBack.setText("VOLVER");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, 39));

        movieGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drama", "Comedia", "Deportivo", "Cultural" }));
        getContentPane().add(movieGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 237, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMovieActionPerformed
        
        if(this.validateMovieName()){
            if(this.validateID()){
                        if(!Cartelera.firstMovie){
                            Pelicula m = new Pelicula(this.movieName.getText(), this.movieGenre.getSelectedItem().toString(), Integer.parseInt(this.movieID.getText()));
                            this.newMovies = new Pelicula[1];
                            this.newMovies[0] = m;
                            Cartelera.firstMovie=true;
                            MovieIndex[] mi = new MovieIndex[1];
                            MovieIndex index = new MovieIndex(m.getID(),0);
                            mi[0] = index;
                            Cartelera.movieIndexes = mi;
                            Cartelera.movies=this.newMovies;
                            this.setVisible(false); 
                        } else {
                            int indiceTemp = Cartelera.buscarPelicula(Integer.parseInt(this.movieID.getText()));
                            if(indiceTemp==-1){
                                Pelicula m = new Pelicula(this.movieName.getText(), this.movieGenre.getSelectedItem().toString(), Integer.parseInt(this.movieID.getText()));
                                this.newMovies = new Pelicula[this.movies.length + 1];
                                MovieIndex[] mi = new MovieIndex[this.newMovies.length];
                                MovieIndex index = new MovieIndex(m.getID(),mi.length-1);

                                for (int i = 0; i < this.movies.length; i++) {
                                    this.newMovies[i]=this.movies[i];
                                    mi[i]=Cartelera.movieIndexes[i];
                                }
                                this.newMovies[this.newMovies.length-1]=m;
                                mi[mi.length-1]=index;
                                mi=this.ordenarIndices(mi);
                                Cartelera.movieIndexes=mi; 
                                Cartelera.movies=this.newMovies;
                                this.setVisible(false); 
                            } else {
                                JOptionPane.showMessageDialog(this, "El ID ya pertenece a la película titulada \""+Cartelera.movies[indiceTemp].getName()+"\"", "ERROR", JOptionPane.ERROR_MESSAGE);
                                this.movieID.setText("");
                            }
                        }
            } else {
                JOptionPane.showMessageDialog(this, "El ID es inválido.\nDebe ser un número entero entre el 1 y el 999999", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El nombre de la película debe ser máximo de 30 caracteres.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
          
    }//GEN-LAST:event_CreateMovieActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new CreateMovie().setVisible(true);
            }
        });
    }
    
    public boolean validateMovieName(){
        if(!this.movieName.getText().isEmpty() && this.movieName.getText().length()<31){
            return true;
        } else {
            return false;
        }
    }
    
    public boolean validateID(){
        if(!this.movieID.getText().isEmpty() && this.movieID.getText().length()<7){
            if(Metodos.isNumeric(this.movieID.getText())){
                if((Integer.parseInt(this.movieID.getText()))<1000000 && (Integer.parseInt(this.movieID.getText()))>0){
                    return true;
                }else {
                    return false;
                }
            } else {
                return false;
            }
        }else{
            return false;
        }
    }
    
    
    public MovieIndex[] ordenarIndices(MovieIndex[] newMIs){
        for (int i = 0; i < newMIs.length - 1; i++){
            int min = i;
            for (int j = i + 1; j < newMIs.length; j++){
                if (newMIs[j].getMovieID()< newMIs[min].getMovieID()){
                    min = j;
                }
            }
            if (i != min){
                MovieIndex aux= newMIs[i];
                newMIs[i] = newMIs[min];
                newMIs[min] = aux;
            }
        }
        return newMIs;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateMovie;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> movieGenre;
    private javax.swing.JTextField movieID;
    private javax.swing.JTextField movieName;
    // End of variables declaration//GEN-END:variables
}
