/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Blockbuster;

import javax.swing.JOptionPane;

/**
 *
 * @author victoriaacuna
 */
public class EditUser extends javax.swing.JFrame {

    /**
     * Creates new form EditUser
     */
    public EditUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditUser = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userCI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditUser.setText("GUARDAR CAMBIOS");
        btnEditUser.setEnabled(false);
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 489, 150, 39));

        btnGoBack.setText("VOLVER");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 489, 150, 39));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICAR USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtUserName.setEnabled(false);
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 353, 226, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUEVO NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 358, -1, -1));

        btnSearch.setText("BUSCAR");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 247, 150, 37));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÉDULA ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 163, 101, -1));
        getContentPane().add(userCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 158, 226, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(Cartelera.firstUser){
            if(this.validateCI()){
                int userCI = Integer.parseInt(this.userCI.getText().substring(1));
                String userLiteralCI = this.userCI.getText().substring(0,1);
                int pos = Cartelera.buscarUsuario(userCI, userLiteralCI);
                if(pos!=-1){
                    this.btnEditUser.setEnabled(true);
                    this.txtUserName.setEnabled(true);
                    this.txtUserName.setText(Cartelera.users[pos].getName());
                } else {
                    JOptionPane.showMessageDialog(this, "La cédula no está inscrita en el sistema.\nPor favor validar que esté correctamente escrita.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    this.btnEditUser.setEnabled(false);
                    this.txtUserName.setEnabled(false);
                    this.userCI.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cédula inválida.\nDebe seguir el siguiente formato: A99999999", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.btnEditUser.setEnabled(false);
                this.txtUserName.setEditable(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ningún usuario registrado en la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        if(this.validateUsername()){
            if(this.validateCI()){
                int userCI = Integer.parseInt(this.userCI.getText().substring(1));
                String userLiteralCI = this.userCI.getText().substring(0,1);
                int pos = Cartelera.buscarUsuario(userCI, userLiteralCI);
                if(pos!=-1){
                    Cartelera.users[pos].setName(this.txtUserName.getText());
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "La cédula no está inscrita en el sistema.\nPor favor validar que esté correctamente escrita.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    this.btnEditUser.setEnabled(false);
                    this.txtUserName.setEnabled(false);
                    this.userCI.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cédula inválida.\nDebe seguir el siguiente formato: A99999999", "ERROR", JOptionPane.ERROR_MESSAGE);
                this.btnEditUser.setEnabled(false);
                this.txtUserName.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El nombre ha de tener como máximo 30 caracteres.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EditUser().setVisible(true);
            }
        });
    }
    
    public boolean validateCI(){
        
        if(!this.userCI.getText().isEmpty() && this.userCI.getText().length()<10 && this.userCI.getText().length()>1){
            String literalID = this.userCI.getText().substring(0, 1);
            String numericID = this.userCI.getText().substring(1);
            boolean isNumeric = Metodos.isNumeric(numericID);
            boolean isLiteral = Metodos.isNumeric(literalID);
            
            if(isNumeric && !isLiteral){
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
    
    public boolean validateUsername(){
        if(!this.txtUserName.getText().isEmpty() && this.txtUserName.getText().length()<31){
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField userCI;
    // End of variables declaration//GEN-END:variables
}
